### ISSUE TITLE
Add installVersion.R script to install particular CRAN package versions

### ISSUE THREAD

**Issue by aaron0browne** [eddelbuettel/littler#15] opened 2015-02-26 15:19 UTC
This is a feature request for the ability to specify versions for installed R packages. I am using the littler scripts in a Docker image, following the patterns I see in the rocker github organization, and would like the ability to pin installation versions so my builds are entirely predictable.

**Comment by eddelbuettel** [comment] 2015-02-26 15:35
How would you do that at the R level?   I think that is outside the scope of `littler`. 

There are folks who obsess much more than I do over installing particular versions, and some contribute to Rocker / Docker.  To me, if you want to / need to freeze a particular version the obvious way to do so would be to ... include it in the container!

So unless you convince me otherwise I'd like to close this.

**Comment by aaron0browne** [comment] 2015-02-26 15:56
I was thinking of using the `devtools::install_version` function. Let me throw up a PR.

**Comment by eddelbuettel** [comment] 2015-02-26 16:18
I still don;t think it belongs into littler -- so why not just make it a local file? Take inspiration from install2.r or install_github,r.

**Comment by aaron0browne** [comment] 2015-02-26 17:12
To answer your questions:

1. Why not include it in the container? We were chaining `curl` and `R CMD INSTALL` commands in our Dockerfile, and wanted to move to `r-base` and `littler` for readability and maintainability.
2. Why not make a local file? I'd like to have it available for use in multiple Dockerfiles without maintaining duplicate code across the repositories or an entirely separate repo just for this.

Take a look at the PR and let me know what you think. I won't be offended if you stick to your guns and decide to close it.

**Comment by eddelbuettel** [comment] 2015-02-26 17:35
It is a clean enough PR but I still won't take it as I don't like devtools and the chain of depends it brings in.  `install.r` needs nothing; `install2.r` currently needs a single package (ie docopt).  

But devtools, on the other hand, installs "half of CRAN":

>  Imports: httr (≥ 0.4), RCurl, utils, tools, methods, memoise, whisker, evaluate, \
>  digest, rstudioapi (≥ 0.2.0), jsonlite, roxygen2 (≥ 4.1.0)

and would force this eg into some of the minimal Docker containers where we use it.  

So, sorry.  It's still going to be "nope" from my end unless someone changes my mind.  Paging @cboettig on that issue...

**Comment by cboettig** [comment] 2015-02-26 17:55
This looks quite useful to me; but Dirk has a good point about being able to use `install2.r` without having to install `devtools` on the image first.  Given that `littler` is in the official r-base and `devtools` is not, it looks to me like this would break any Dockerfile that has currently been built on `r-base` and makes use of `install2.r`, since the `library(devtools)` call would fail. 

Given that there is already `install.r` and `installGithub.r`, why not provide this feature as a separate script (`installVersion.r`)?  This also makes the mapping to different functions more transparent and should avoid breaking any existing setups.

**Comment by aaron0browne** [comment] 2015-02-26 18:07
Updated the PR with a separate script.

**Comment by eddelbuettel** [comment] 2015-02-26 19:02
> Given that there is already install.r and installGithub.r, ...

Why not as a _modification_ of `installGithub,r`  ?

**Comment by cboettig** [comment] 2015-02-26 19:05
Wouldn't it be confusing for a command that reads: `installGithub.r  <args> packageFoo` to install a package from CRAN?

**Comment by eddelbuettel** [comment] 2015-02-26 19:14
Never mind, my thinko.  

But I still don't like the whole idea of the script and would rather see it on a gist somewhere than in littler ...   I believer in repositories, and install(2).r works off those.

**Comment by cboettig** [comment] 2015-02-26 19:26
I'm still a bit confused -- `install_version` also works on (CRAN-style) repositories; it's just a wrapper around `install.packages()`.  It just appears to navigate through CRAN's archive (or any other repository's archive that follows the CRAN convention of `/src/contrib/Archive` I think)

**Comment by aaron0browne** [comment] 2015-02-26 20:19
Yes, `install_version` just installs particular versions from the CRAN (or other) repo. You can see the code [here](https://github.com/hadley/devtools/blob/master/R/install-version.r) and verify it is just a wrapper for `install.packages`.

**Comment by aaron0browne** [comment] 2015-03-04 17:04
Any thoughts about merging the associated PR for this #16?

**Comment by eddelbuettel** [comment] 2015-03-04 17:11
Sorry, got busy with Rcpp the last few days.

I think on  the margin this is a useful command, but I don't think we want a devtools dependency.  

The `install_version()` code you linked to has _almost_ no dependency:  all but the last line.  And given a URL, it is a matter of `tempfile()`, `download.file()` and `install.packages()` to deploy that.  So I think someone (you, me, ...) should write a new variant for littler with no dependency beyond docopt.

**Comment by aaron0browne** [comment] 2015-03-04 17:15
Maybe I'm missing something. Doesn't `installGithub.r` already [depend](https://github.com/eddelbuettel/littler/blob/master/examples/installGithub.r#L11) on `devtools`?

**Comment by eddelbuettel** [comment] 2015-03-04 17:31
We are going in circles, so I will just close this.

**Closed by eddelbuettel** 2015-03-04 17:31 UTC

**Comment by nihonjinrxs** [comment] 2017-02-15 20:31
I'd like for you to reopen this one.  The `devtools` dependency concern doesn't exist any longer.

The ability to install specific package versions is necessary for engineering production R systems in Docker containers where you want reproducibility, and the `remotes` package that is [already a dependency](https://github.com/eddelbuettel/littler/blob/master/inst/examples/installGithub.r) in `installGithub.r` provides a similar `install_version` method that replicates what the `devtools` package does.

Any chance we can reopen and tackle this now?

**Comment by cboettig** [comment] 2017-02-15 20:51
@nihonjinrxs just a side note that you can install from specific CRAN snapshots by just passing the appropriate MRAN repo URL to `install2.r` using the `--repos` argument.  Not quite the same as specifying the package version; though from a reproducibility standpoint it's often easier and more reliable to specify a date rather than a version. (e.g. since many CRAN packages are not explicit about versions of their dependencies, and CRAN's automated checks only ensure things are working with the version of packages at the time of submission.  

If you're looking to install specific versions in Docker containers where you want reproducibility, you might take a look at https://hub.docker.com/r/rocker/r-ver/ where most of this is done somewhat automatically for you (i.e. packages install from the MRAN snapshot at the date the requested version of R was current).  Feedback on this approach definitely welcome on the r-ver repo

**Comment by nihonjinrxs** [comment] 2017-02-15 21:02
@cboettig thanks -- this helps quite a bit.  I had pulled my own copy of r-base and was stable-versioning that, but the r-ver option is nice.  Is there perhaps a stable-versioned rocker/shiny?

**Comment by eddelbuettel** [comment] 2017-02-15 21:21
I am locking this now as it has nothing to do with littler.

If ever you write yourself a helper script, and think it is general enough, consider submitting it here. Until then this is mostly a problem at your end, and nothing littler needs.
